repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-yaml
    - id: detect-private-key
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.2
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]
    - id: check-github-actions
      args: ["--verbose"]
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      args: [ '-w' ]
    # - id: go-vet
    - id: go-mod-tidy
    - id: go-test-mod