services:
  firelink:
    build: .
    ports:
      - "8080:8080"
    # If you use environment variables for DB, etc.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=firelink
    # Uncomment if you want to wait for DB, etc.
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: firelink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - firelink

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboards:/var/lib/grafana/dashboards
      - ./provisioning/dashboards:/var/lib/grafana/provisioning
    depends_on:
      - prometheus

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://yourusername:yourpassword@postgres:5432/firelink?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres

volumes:
  pgdata:
