services:
  firelink:
    build: .
    ports:
      - "8080:8080"
    # If you use environment variables for DB, etc.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=firelink
    # Uncomment if you want to wait for DB, etc.
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: firelink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
